baseURL = "https://liusulin.github.io/"
languageCode = "en-us"
title = "Sulin Liu"
theme = "hugo-ht"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
enableRobotsTXT = true
enableGitInfo = true
googleAnalytics = "UA-173624094-1"

[permalinks]
cn = "/cn/:year/:month/:day/:slug/"
en = "/en/:year/:month/:day/:slug/"
posts = "/posts/:year/:month/:day/:slug/"

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.en]]
    name = "Publications"
    url = "/en/publications/"
    weight = 2
# [[menu.en]]
#     name = "Posts"
#     url = "/en/posts/"
#     weight = 3
# [[menu.en]]
#     name = "中文"
#     url = "/cn/posts/"
#     weight = 3
# [[menu.cn]]
#     name = "关于"
#     url = "/cn/about/"
#     weight = 1
# [[menu.cn]]
#     name = "关于"
#     url = "/cn/about/"
#     weight = 1
# [[menu.cn]]
#     name = "日志"
#     url = "/cn/posts/"
#     weight = 2
# [[menu.cn]]
#     name = "English"
#     url = "/"
#     weight = 3

[params]
    description = "Peronal website of Sulin Liu"
    homeText = "Peronal website of Sulin Liu"
    # Please make sure `blogDirNmae` matches the name used in `menu` above:
    blogDirName = "posts"
    # singleLang = true
    defaultLang = "en"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs" 
    MathJaxVersion = "2.7.5"
    favicon = "/media/mit_favicon.ico"
    # Edit by yourself:
    GithubEdit = "https://github.com/liusulin/liusulin.github.io/edit/master/content/"
    copyright = "&copy;"
    copyrightYear = "2022"
    # Edit by yourself:
    GithubRepo = "https://github.com/liusulin/liusulin.github.io"
    # Edit by yourself:
    ContentSource = "https://raw.githubusercontent.com/liusulin/liusulin.github.io/master/content/" 

[params.logo]
  url = "/media/MIT-logo-red-gray.png" # you can change it
  alt = "MIT logo"


[params.lang]

    [params.lang.author]
      en = "Sulin Liu"
      cn = "刘苏林"

    [params.lang.madeWith]
      en = "Made with"
      cn = "本站驱动"

    [params.lang.edit]
      en = "Suggest an edit of this page"
      cn = "编辑本页"

    [params.lang.lastupdate]
      en = "Last modified on"
      cn = "最后一次修改于"

    [params.lang.Sitelastupdate]
      en = "Site last updated on"
      cn = "最近一次更新于"

    [params.lang.sourceCode]
      en = "Content in"
      cn = "内容存于"

    [params.lang.subscribe]
      en = "Subscribe"
      cn = "订阅"

    [params.lang.license]
      en = "License"
      cn = "版权"

[markup]
 defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false
  
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2

[imaging]
quality = 100